config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bugs do
    get 'search', on: :collection
  end  
resources :projects

root "projects#index"




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  require 'sidekiq/web'
  
mount Sidekiq::Web => '/sidekiq'
resources :projects do
  collection do
    get 'search' 
  end
end

resources :bugs do
  post :assign, on: :member
end
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :bugs, dependent: :destroy
    has_many :project_users,dependent: :destroy
    has_many :users, through: :project_users
    accepts_nested_attributes_for :users
    belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
    belongs_to :developer, class_name: "User", foreign_key: "user_id", optional: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :authenticate_user!
    load_and_authorize_resource
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    def index
      
       # @projects=Project.all
       if params.present?
        @projects = Project.where('LOWER(name) LIKE ?', "%#{params["query"]}%")


       else
        @projects = Project.accessible_by(current_ability)
       end
        

        #@projects = current_user.projects
        respond_to do |format|
          format.html { render 'index' }
          format.json { render json: @projects }
        end
        
        end
      
        def show
          @project=Project.find(params[:id])
          
          
        end
      
        def edit
          @project=Project.find(params[:id])
      
        end
      
        def new
          @project=Project.new
          

        end
      
        def create
          
          @project = Project.new(project_params)
          @project.creator_id = current_user.id

          if @project.save
            @user = User.find(@project.user_id) 
    MyFirstJob.perform_in(5.seconds, @project.user_id) 
    UserMailer.welcome_email(@user, @project).deliver_now 


            redirect_to projects_path, notice: 'Project was successfully created.'
          else
            render :new, status: :unprocessable_entity
          end
        end
      
      
      
        def destroy
          @project = Project.find(params[:id])
          @project.destroy
      
          redirect_to root_path, status: :see_other
        end
        
        def edit
          @project=Project.find(params[:id])
        end
        

        def update
          @project=Project.find(params[:id])
          
      
          if @project.update(project_params)
            
            current_user = User.find(params[:project][:user_id])
            update_details = "Project '#{params[:project][:name]}' has been updated."
            MySeconedJob.perform_async(@project.id, current_user.id, update_details)       
            
            redirect_to @project, notice: 'Project was successfully updated.'
      
          else
            render :edit, status: :unprocessable_entity
          end
        end
        
        
  
         
      
        
         private
         
         
      
       
        
      def project_params
       # params.require(:project).permit(:name, users_attributes: [:id,:user_id, :name, :email])
       params.require(:project).permit(:name,:description, :query, :user_id, :creator_id, users_attributes: [:id, :name, :email])

      end
      
   def set_project
    @project = Project.find(params[:id])
  end


  

  
end 

    

app/helpers/projects_helper.rb
module ProjectsHelper
    
end

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.where(role: [:qa, :developer]), :id, :name, prompt: true %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render "form", project: @project %>

<%= link_to "Show", @project %>
<%= link_to "Back", projects_path %>

app/views/projects/index.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Live Search with jQuery</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
</head>
<body>



  <h1>Welcome to App!</h1>
  <h4>An email will be sent to this address containing a confirmation link.</h4>
  <%= button_to("Sign Up", '/signup', method: :get) %>
  <h6>Thank you for using this app!</h6>

  <h1>Welcome to the project</h1>
  <% if user_signed_in? %>
    <p>Signed in as <%= current_user.role %>.</p>
    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= button_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
  <% end %>

  <div style="margin-top: 50px;"></div>

<input type="text" id="search-input" placeholder="Search projects...">
<ul id="search-results"></ul>

  
  <h1>Projects</h1>
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.name, project %></li>
    <% end %>
  </ul>

  <% if can? :create, Project %>
    <%= link_to "New project", new_project_path %>
  <% end %>

  <div style="margin-top: 50px;"></div>

  <% if can? :create, Bug %>
    <%= link_to "New Bug", new_bug_path, class: 'btn btn-primary' %>
  <% end %>

  <div style="margin-top: 50px;"></div>

<script>

$(document).ready(function(){
      function searchProjects(query) {
        $.ajax({
          url: '/',
          method: 'GET',
          data: { query: query },
          dataType: 'json',
          success: function(response) {
            $('#search-results').empty();

            if (response.length > 0) {
              response.forEach(function(project) {
                $('#search-results').append('<li>' + project.name + ' - ' + project.description + '</li>');
              });
            } else {
              $('#search-results').append('<li>No results found</li>');
            }
          },
          error: function(xhr, status, error) {
            console.error('Error fetching results:', error);
            console.log('Server response:', xhr.responseText);
            $('#search-results').empty().append('<li>Error fetching results</li>');
          }
        });
      }

      $('#search-input').on('input', function() {
        var query = $(this).val();
        searchProjects(query);
      });
    });
  </script>
</body>
</html>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p>Creator: <%= @project.creator.try(:name) || 'Unknown' %></p>
<p>Assign_to: <%= @project.developer.try(:name) || 'Unknown' %></p>


<ul>
  <li><%= link_to "Edit", edit_project_path(@project) %></li>
  <li><%= link_to "Destroy", project_path(@project), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h2>Bugs associated with this project:</h2>

<ul>
  <% @project.bugs.each do |bug| %>
    <p>Title: <%= link_to bug.title, bug_path(bug) %></p>   
      
  <% end %>
</ul>

<%= link_to "Back", projects_path %>