config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bugs do
    get 'search', on: :collection
  end  
resources :projects

root "projects#index"




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  require 'sidekiq/web'
  
mount Sidekiq::Web => '/sidekiq'
resources :projects do
  collection do
    get 'search' 
  end
end

resources :bugs do
  post :assign, on: :member
end
end

app/models/bug.rb
class Bug < ApplicationRecord
belongs_to :user
belongs_to :project
belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'


enum status: { newly: 0, started: 1, completed: 2, resolved: 3 }
  enum bug_type: { feature: 0, bug: 1 }

  validates :title, uniqueness: { scope: :project_id, message: "should be unique within the project" }

  has_one_attached :avatar
  validate :validate_avatar_format
  validates :bug_type, presence: true
  validates :status, presence: true





  


  private

  def validate_avatar_format
    if avatar.attached? && !avatar.content_type.in?(%w(image/png image/gif))
      errors.add(:avatar, 'must be a PNG or GIF image')
    end
  end
  def bug_status_options
    if feature?
      %w(newly started completed)
    elsif bug?
      %w(newly started resolved)
    else
      []
    end
  end

  public
  
  def status_options_for_form
    bug_status_options.map { |status| [status.capitalize, status] }
  end
  

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    before_action :set_bug, only: [:show, :edit, :update, :destroy,:assign]

    def index
       # @bugs=Bug.all
        @bugs = Bug.accessible_by(current_ability)
        
        end
      
        def show
          @bug=Bug.find(params[:id])
        end
      
        def edit
          @bug=Bug.find(param[:id])
          @projects = Project.all

      
        end
      
        def new
          @bug=Bug.new
          @projects = Project.all

        end
      
        def create
          @bug = Bug.new(bug_params)
          @bug.creator_id = current_user.id

          
          

          if @bug.save
            user = @bug.user
            MyBugCreationJob.perform_async(@bug.id, user.id)
            redirect_to @bug, notice: 'Bug was successfully created.'
          
    
           else
            @projects = Project.all 
            render :new, status: :unprocessable_entity
          end
        end
      
      
      
        def destroy
          @bug = Bug.find(params[:id])
          @bug.destroy
      
          redirect_to root_path, status: :see_other
        end
        
        def edit
          @bug=Bug.find(params[:id])
        end
      
        def update
          @bug=Bug.find(params[:id])
          
      
          if @bug.update(bug_params)
            redirect_to @bug
          else
            render :edit, status: :unprocessable_entity
          end
        end

        def assign
          @bug.update(user_id: current_user.id)
          redirect_to bugs_path, notice: 'Bug was successfully assigned to yourself.'
        end
      
         private
      
      def bug_params
        params.require(:bug).permit(:title, :description,:deadline,:bug_type,:status,:avatar,:user_id, :project_id,:creator_id)
      
      end
      def set_bug
        @bug = Bug.find(params[:id])
      end

      

     
      
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_with model: @bug do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

 <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_field :deadline %>
  </div>

 <div class="field">
  <%= form.label :bug_type %>
  <%= form.collection_radio_buttons :bug_type, [['Feature', 'feature'], ['Bug', 'bug']], :last, :first %>
</div>
<div class="field" id="status-field">
  <%= form.label :status %>
  <%= form.select :status, options_for_select(@bug.status_options_for_form), include_blank: true %>
</div>


 <div class="field">
  <%= form.label :user_id %>
  <% developers = User.where(role: :developer) %>
  <%= form.collection_select :user_id, developers, :id, :name, prompt: true %>
</div>

<div class="field">
  <%= form.label :project_id %>
  <% all_projects = Project.all %>
  <%= form.collection_select :project_id, all_projects, :id, :name, prompt: "Please select" %>
</div>




   <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


  <div style="margin-top: 100px;"></div>


<% if @projects.present? %>

<% @projects.each do |project| %>
  <h2>Project: <%= project.name %></h2>
  <p><strong>Creator:</strong> <%= project.creator.name %></p>
  <% if project.developer %>
    <p><strong>assign_to:</strong> <%= project.developer.name %></p>
  <% end %>
  <h3>Bugs associated with this project:</h3>
  <ul>
    <% project.bugs.each do |bug| %>
    <p>Title: <%= bug.title %></p>   
      <p>Description: <%= bug.description %></p>

    <% end %>
  </ul>
<% end %>
<% end %>

app/views/bugs/edit.html.erb
<h1>Edit bug</h1>

<%= render "form", bug: @bug %>

app/views/bugs/index.html.erb
<h1>Project Details</h1>

<p><strong>Creator:</strong> <%= @project.creator.name %></p>

<h2>Bugs associated with this project:</h2>

<% @project.bugs.each do |bug| %>
  <p>
    <strong>Title:</strong> <%= bug.title %><br>
    <strong>Description:</strong> <%= bug.description %><br>
    <% if current_user.developer? && can?(:assign, Bug) %>
      <%= button_to "Assign to Myself", assign_bug_path(bug), method: :post, data: { confirm: "Are you sure you want to assign this bug to yourself?" } %>
    <% end %>
  </p>
<% end %>

<%= link_to "Back", projects_path %>

app/views/bugs/new.html.erb
<h1>New bug</h1>

<%= render "form", bug: @bug %>

app/views/bugs/show.html.erb
<h1><strong>Title:</strong> <%= @bug.title %></h1>
<p><strong>Description:</strong> <%= @bug.description %></p>
<p><strong>deadline:</strong> <%= @bug.deadline %></p>
<p><strong>Status:</strong> <%= @bug.status %></p>
<p><strong>Bug_Type:</strong> <%= @bug.bug_type %></p>
<ul>

<% if @bug.avatar.attached? %>
  
    <%= image_tag @bug.avatar, size: "80x80" %>
  <% end %>

  <li><%= link_to "Edit", edit_bug_path(@bug) %></li>
     <li><%= link_to "Destroy", bug_path(@bug), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </li>

</ul>

<%= link_to "Back", projects_path %>